package br.ulbra.view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno.saolucas
 */
public class ChamadoView extends javax.swing.JFrame {

    /**
     * Creates new form ChamadoView
     */
    public ChamadoView() {
        initComponents();
        listarTabela();
        this.setLocationRelativeTo(null);

    }

    public void listarTabela() {
        DefaultTableModel model = (DefaultTableModel) tblChamado.getModel();
        model.setRowCount(0);

        java.util.List<br.ulbra.model.Chamado> lista = controller.listar();

        if (lista != null) {
            for (br.ulbra.model.Chamado c : lista) {
                model.addRow(new Object[]{
                    c.getId(),
                    c.getSolicitante(),
                    c.getSala(),
                    c.getEquipamento_tag(),
                    c.getProblema_relatado(),
                    c.getDiagnostico_tecnico(),
                    c.getPrioridade(),
                    c.getStatus(),
                    c.getData_abertura()
                });
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum chamado encontrado!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbPrioridade = new javax.swing.JComboBox<>();
        txtSolicitante = new javax.swing.JTextField();
        txtSala = new javax.swing.JTextField();
        txtEquipamentoTag = new javax.swing.JTextField();
        txtProblema = new javax.swing.JTextField();
        txtDiagnosticoTecnico = new javax.swing.JTextField();
        txtDataAbertura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jcbStatus = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnExcliur = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChamado = new javax.swing.JTable();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcbPrioridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Media", "Baixa", "Alta" }));
        jcbPrioridade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbPrioridadeMouseClicked(evt);
            }
        });
        jcbPrioridade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPrioridadeActionPerformed(evt);
            }
        });

        txtSolicitante.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtSolicitante.setBorder(javax.swing.BorderFactory.createTitledBorder("SOLICITANTE"));
        txtSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSolicitanteActionPerformed(evt);
            }
        });

        txtSala.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtSala.setBorder(javax.swing.BorderFactory.createTitledBorder("SALA"));
        txtSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaActionPerformed(evt);
            }
        });

        txtEquipamentoTag.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtEquipamentoTag.setBorder(javax.swing.BorderFactory.createTitledBorder("TAG DO EQUIPAMENTO"));

        txtProblema.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtProblema.setBorder(javax.swing.BorderFactory.createTitledBorder("PROBLEMA RELATADO"));

        txtDiagnosticoTecnico.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtDiagnosticoTecnico.setBorder(javax.swing.BorderFactory.createTitledBorder("DIAGNOSTICO TECNICO"));

        txtDataAbertura.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtDataAbertura.setBorder(javax.swing.BorderFactory.createTitledBorder(" DATA ABERTURA"));

        jLabel1.setText("PRIORIDADE");

        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendente", "Concluido", "Em progresso" }));
        jcbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbStatusActionPerformed(evt);
            }
        });

        jLabel2.setText("STATUS");

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("e");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpa");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnExcliur.setText("x");
        btnExcliur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcliurActionPerformed(evt);
            }
        });

        tblChamado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "SOLICITANTE", "SALA", "TAG EQUIPAMENTO", "PROBLEMA RELATADO", "DIAGNOSTICO TEC", "PRIORIDADE", "STATUS", "DATA DE ABERTURA"
            }
        ));
        tblChamado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChamadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChamado);

        txtId.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDiagnosticoTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jcbPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEquipamentoTag, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtProblema, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSala, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnSalvar)
                .addGap(105, 105, 105)
                .addComponent(btnLimpar)
                .addGap(100, 100, 100)
                .addComponent(btnExcliur)
                .addGap(68, 68, 68)
                .addComponent(btnEditar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSala, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(txtSolicitante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtProblema, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(txtEquipamentoTag))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDiagnosticoTecnico, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(txtDataAbertura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcbPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpar)
                        .addComponent(btnExcliur)
                        .addComponent(btnEditar))
                    .addComponent(btnSalvar))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbPrioridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPrioridadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPrioridadeActionPerformed

    private void jcbPrioridadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbPrioridadeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbPrioridadeMouseClicked

    private void txtSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSolicitanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSolicitanteActionPerformed

    private void txtSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaActionPerformed

    private void jcbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbStatusActionPerformed

    private void tblChamadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChamadoMouseClicked
        int linha = tblChamado.getSelectedRow();
        txtId.setText(tblChamado.getValueAt(linha, 0).toString());
        txtSolicitante.setText(tblChamado.getValueAt(linha, 1).toString());
        txtSala.setText(tblChamado.getValueAt(linha, 2).toString());
        txtEquipamentoTag.setText(tblChamado.getValueAt(linha, 3).toString());
        txtProblema.setText(tblChamado.getValueAt(linha, 4).toString());
        txtDiagnosticoTecnico.setText(tblChamado.getValueAt(linha, 5).toString());
        jcbPrioridade.setSelectedItem(tblChamado.getValueAt(linha, 6).toString());
        jcbStatus.setSelectedItem(tblChamado.getValueAt(linha, 7).toString());
        txtDataAbertura.setText(tblChamado.getValueAt(linha, 8).toString());

    }//GEN-LAST:event_tblChamadoMouseClicked
    br.ulbra.controller.ChamadoController controller = new br.ulbra.controller.ChamadoController();
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        String mensagem = controller.cadastrar(
                txtSolicitante.getText(),
                txtSala.getText(),
                txtEquipamentoTag.getText(),
                txtProblema.getText(),
                txtDiagnosticoTecnico.getText(),
                jcbPrioridade.getSelectedItem().toString(),
                jcbStatus.getSelectedItem().toString(),
                txtDataAbertura.getText()
        );

        javax.swing.JOptionPane.showMessageDialog(null, mensagem);
        listarTabela();

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtId.setText(null);
        txtSolicitante.setText(null);
        txtSala.setText(null);
        txtEquipamentoTag.setText(null);
        txtProblema.setText(null);
        txtDiagnosticoTecnico.setText(null);
        jcbPrioridade.setName(null);
        jcbStatus.setSelectedItem("Pendente");
        jcbPrioridade.setSelectedItem("Media");
        txtDataAbertura.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnExcliurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcliurActionPerformed
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um chamado primeiro!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                null,
                "Deseja excluir o Problema relatado " + txtProblema.getText() + " ? ",
                "Exclusão",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {

            Long id = Long.parseLong(txtId.getText());

            String msg = controller.deletar(id);
            JOptionPane.showMessageDialog(null, msg);
            listarTabela();

        } else {
            JOptionPane.showMessageDialog(null, "Operação cancelada!");
        }

    }//GEN-LAST:event_btnExcliurActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um chamado primeiro!");
            return;
        }

        Long id = Long.parseLong(txtId.getText());

        String msg = controller.atualizar(
                id,
                txtSolicitante.getText(),
                txtSala.getText(),
                txtEquipamentoTag.getText(),
                txtProblema.getText(),
                txtDiagnosticoTecnico.getText(),
                jcbPrioridade.getSelectedItem().toString(),
                jcbStatus.getSelectedItem().toString(),
                txtDataAbertura.getText()
        );

        JOptionPane.showMessageDialog(null, msg);
        listarTabela();


    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChamadoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcliur;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbPrioridade;
    private javax.swing.JComboBox<String> jcbStatus;
    private javax.swing.JTable tblChamado;
    private javax.swing.JTextField txtDataAbertura;
    private javax.swing.JTextField txtDiagnosticoTecnico;
    private javax.swing.JTextField txtEquipamentoTag;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtProblema;
    private javax.swing.JTextField txtSala;
    private javax.swing.JTextField txtSolicitante;
    // End of variables declaration//GEN-END:variables
}
