/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

/**
 *
 * @author aluno.saolucas
 */
public class DashBoardView extends javax.swing.JFrame {

    /**
     * Creates new form DashBoardView
     */
    public DashBoardView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmCadaEqui = new javax.swing.JMenuItem();
        jmCadaUsu = new javax.swing.JMenuItem();
        jmCadaCha = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMConUsu = new javax.swing.JMenuItem();
        jMConsEqui = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(57, 48, 83));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastros");

        jmCadaEqui.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmCadaEqui.setText("Cadastro Equipamentos");
        jmCadaEqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadaEquiActionPerformed(evt);
            }
        });
        jMenu1.add(jmCadaEqui);

        jmCadaUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jmCadaUsu.setText("Cadastro Usuarios");
        jmCadaUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadaUsuActionPerformed(evt);
            }
        });
        jMenu1.add(jmCadaUsu);

        jmCadaCha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmCadaCha.setText("Cadastro Chamados");
        jmCadaCha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadaChaActionPerformed(evt);
            }
        });
        jMenu1.add(jmCadaCha);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consulta");

        jMConUsu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMConUsu.setText("Consulta Usuario");
        jMConUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConUsuActionPerformed(evt);
            }
        });
        jMenu2.add(jMConUsu);

        jMConsEqui.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMConsEqui.setText("Consulta Equipamento");
        jMConsEqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConsEquiActionPerformed(evt);
            }
        });
        jMenu2.add(jMConsEqui);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Sobre");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCadaUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadaUsuActionPerformed
        this.dispose(); // fecha a tela de login
        new UsuarioView().setVisible(true); // abre a próxima tela
    }//GEN-LAST:event_jmCadaUsuActionPerformed

    private void jmCadaChaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadaChaActionPerformed
        this.dispose(); // fecha a tela de login
        new ChamadoView().setVisible(true); // abre a próxima tela
    }//GEN-LAST:event_jmCadaChaActionPerformed

    private void jMConsEquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsEquiActionPerformed
        this.dispose();
        new ConsultaEquipamento().setVisible(true);
    }//GEN-LAST:event_jMConsEquiActionPerformed

    private void jmCadaEquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadaEquiActionPerformed
        this.dispose(); // fecha a tela de login
        new EquipamentoView().setVisible(true); // abre a próxima tela
    }//GEN-LAST:event_jmCadaEquiActionPerformed

    private void jMConUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConUsuActionPerformed
        this.dispose(); // fecha a tela de login
        new ConsutaUsuarioview().setVisible(true);
    }//GEN-LAST:event_jMConUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMConUsu;
    private javax.swing.JMenuItem jMConsEqui;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmCadaCha;
    private javax.swing.JMenuItem jmCadaEqui;
    private javax.swing.JMenuItem jmCadaUsu;
    // End of variables declaration//GEN-END:variables
}
